### PR TITLE
Update acg_classes.lst

### PR DESCRIPTION
**Pull request by Gjorbjond**
Hunter SPELLSTAT should be WIS

### CODE REVIEW

**Comment by LegacyKing** [comment]
Why did you close this?

**Comment by Gjorbjond** [comment]
Thought closing was the last step.  I'm guessing it isn't.

**Comment by LegacyKing** [comment]
Close is cancel the request... One of the maintainers reviews and pulls in the request.

**Comment by Gjorbjond** [comment]
Thanks.  I'll keep that in mind next time.

**Pull request merged**
