### PR TITLE
Various Small Fixes

### PR DESCRIPTION
**Pull request by schofida**
Heroic Path Templates VISIBLE:FALSE
Ability Categories: Fix ErenlanderWeaponFamiliarity typo

### CODE REVIEW

**Comment by LegacyKing** [comment]
This is no longer in newsouces. It's part of the release. I will see if I can salvage this and use it.

**Comment by LegacyKing** [comment]
I can't use this. too many errors I have already fixed, removes product identity tags by PR, and reintroduces bad syntax. Way too many things for me to review and re-fix.

You need to pull the updates from the master branch on pcgen to get the most recent updates. In short, I think you've been using a bad copy, or just the unmodified one in newsources.

I'll look for a VISIBLE:FALSE, and the mention typos.

**Comment by LegacyKing** [comment]
No issues found. I think I cleaned that up during my review process. If you are using github for windows, please switch to sourcetree, or another git client. The github for windows/mac is very limited in abilities and should not be a serious consideration for a contributor doing newsource and bug patches.

**Comment by schofida** [comment]
Aside from being limited, github is also highly inaccurate. I will see about getting sourcetree. Thanks for fixing.

-Dan

**Pull request merged**
