### PR TITLE
Lg beyond the void

### PR DESCRIPTION
**Pull request by axxroytovu**
First commit for Beyond the Void. Lots to do still, but I'm not 100% on how to do templates or archetypes.

### CODE REVIEW

**Comment by Nylanfs** [comment]
Hey Sam, have you done any work on this? We tried to get it included in the latest release but Data lead determined it needed quite a bit of work yet.

**Comment by axxroytovu** [comment]
I was originally waiting to hear back if LG would permit us to use their content. After that it just slipped back and lost all priority. Have we heard from LG? If so I can try and get back into this.

**Comment by Nylanfs** [comment]
Yep we have full permission :)

**Comment by Nylanfs** [comment]
It looks like Gwen did some work on it also, might want to do a merge.

**Comment by Nylanfs** [comment]
Hey Sam, Andrew was reviewing this and saw a bit of empty blocks.

https://pcgenorg.atlassian.net/browse/NEWSOURCE-299

**Pull request merged**
