### PR TITLE
Various Fixes/CS Conditional Aspects

### PR DESCRIPTION
**Pull request by schofida**
Fixed various issues. Added conditional aspects (SkillBonus/CombatBonus/SaveBonus) where needed. Re-design of Racial Abilities

### CODE REVIEW

**Comment by LegacyKing** [comment]
Have conflicts. You able to resolve that?

**Comment by schofida** [comment]
I'm not sure why. I'll check on my lunch break today

**Comment by schofida** [comment]
I just commited an updated midnight_feats. Let me know if that resolved the conflict. (Sorry again, I never used github before)

**Comment by LegacyKing** [comment]
I'm in the middle of updating a core rulebook, so I'll try to walk you through this:

Switch to the master branch, PULL in upstream/ or set up this repo as a remote. git@github.com:PCGen/pcgen-newsources.git

PULL in the master branch, then switch/checkout the branch you are working on. MERGE Master with your current branch. RESOLVE the conflicts. Commit/Push the updates to your repo.

**Comment by schofida** [comment]
Thanks Andrew. I think that I got it. Can you check to see if its resolved?

**Comment by LegacyKing** [comment]
You did it!

**Pull request merged**
