### PR TITLE
NEWSOURCE-427 Add PF1E Tripod Machine source "Oracle's Curse"

### PR DESCRIPTION
**Pull request by pokemonpasta**
NB: Sorry if I mess any of this up, first time using github past just navigating it or downloading stuff. Also my first source I've written up.

The majority of the 3rd party Oracle Curses [on the d20pfsrd page](https://www.d20pfsrd.com/classes/base-classes/Oracle/oracle-curses/#3rd_Party_Curses) are from a single source [published by Tripod Machine in 2014](https://www.opengamingstore.com/products/oracles-curse). I've written all of these (or at least all of the one's on d20pfsrd) up to the best of my ability. All the curses and the choices of spells are in _oc_abilities_class.lst_, and then I have the _oc_abilitycategories.lst_ to make the spell choices work. I apologies for the spacing seemingly messing up as well - it displayed fine locally for me on notepad++, but clearly not here.

DON'T MERGE! I need to add dual-cursed oracle support

### CODE REVIEW

**Comment by jasperbogers** [comment]
Just to be sure: did you check whether this functions in combination with the Dual Cursed Oracle archetype?

**Comment by pokemonpasta** [comment]
I authored this quite a while ago so I'll have to get back and do some testing for that in a bit, but if I don't get a chance I'll make sure to bring it up once we get to data review, if it's not flagged up by the data team themselves

**Review by jasperbogers — APPROVED** [review]

**Comment by pokemonpasta** [comment]
Looking at it it seems I don't have it set up. I'll get on that when I have some time

**Comment by pokemonpasta** [comment]
Haven't done extensive testing for all of the Dual-Cursed Oracle stuff but they build for me at the very least, with no immediate errors in terminal

**Comment by enumag** [comment]
Looks like this got reverted in https://github.com/PCGen/pcgen-newsources/commit/03e26115906c417d2871c5f42aa7f52e0bb8803b. Most likely by accident considering the commit message is unrelated. @LegacyKing @karianna

**Comment by pokemonpasta** [comment]
I see that yeah, this and #623 as well.

**Pull request merged**
